# Generated by Django 4.1.4 on 2022-12-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_contacts_contact_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.skill')),
            ],
        ),
    ]
